CREATE TABLE IF NOT EXISTS RUNNER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(128) NOT NULL UNIQUE,
    NAME VARCHAR(128) NOT NULL,
    STATUS VARCHAR(32) NOT NULL DEFAULT 'INACTIVE',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RUNNER_CONFIG (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    RUNNER_ID BIGINT NOT NULL,
    CONFIG_KEY VARCHAR(128) NOT NULL,
    CONFIG_VALUE TEXT NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_RUNNER_CONFIG_RUNNER FOREIGN KEY (RUNNER_ID) REFERENCES RUNNER (ID) ON DELETE CASCADE,
    UNIQUE (RUNNER_ID, CONFIG_KEY)
);

CREATE TABLE IF NOT EXISTS JOB_HISTORY (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    RUNNER_ID BIGINT NOT NULL,
    JOB_ID BIGINT NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FINISHED_AT TIMESTAMP NULL,
    LOG_PATH TEXT,
    EXIT_CODE INT,
    CONSTRAINT FK_JOB_HISTORY_RUNNER FOREIGN KEY (RUNNER_ID) REFERENCES RUNNER (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RUNNER_CONFIG_FILE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    RUNNER_ID BIGINT NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    CONTENTS TEXT NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_RUNNER_CONFIG_FILE_RUNNER FOREIGN KEY (RUNNER_ID) REFERENCES RUNNER (ID) ON DELETE CASCADE,
    UNIQUE (RUNNER_ID, FILENAME)
);


CREATE INDEX IF NOT EXISTS IDX_JOB_HISTORY_RUNNER ON JOB_HISTORY(RUNNER_ID);
CREATE INDEX IF NOT EXISTS IDX_JOB_HISTORY_JOB ON JOB_HISTORY(JOB_ID);
